# Generated by Django 4.1.3 on 2022-11-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date',)},
        ),
    ]
