# Generated by Django 4.1.3 on 2022-11-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('complete', '-date')},
        ),
    ]
